from fpdf import FPDF
from datetime import datetime
import os

def create_safety_report(max_crowd, alerts_triggered):
    """
    Generates a professional PDF report for crowd analytics.
    """
    pdf = FPDF()
    pdf.add_page()
    
    # 1. Header
    pdf.set_font("Arial", style="B", size=16)
    pdf.cell(200, 10, txt=" Smart Crowd Intelligence", ln=True, align='C')
    pdf.set_font("Arial", style="B", size=14)
    pdf.cell(200, 10, txt="Daily Safety & Incident Report", ln=True, align='C')
    pdf.ln(10) # Line break
    
    # 2. Analytics Data
    pdf.set_font("Arial", size=12)
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    pdf.cell(200, 10, txt=f"Report Generated On: {current_time}", ln=True)
    pdf.cell(200, 10, txt="---------------------------------------------------------", ln=True)
    pdf.cell(200, 10, txt=f"Peak Crowd Density Detected: {max_crowd} People", ln=True)
    pdf.cell(200, 10, txt=f"Total AI Safety Alerts Triggered: {alerts_triggered}", ln=True)
    pdf.cell(200, 10, txt="System Status: ACTIVE & MONITORING", ln=True)
    pdf.cell(200, 10, txt="---------------------------------------------------------", ln=True)
    
    pdf.ln(20)
    
    # 3. Footer
    pdf.set_font("Arial", style="I", size=10)
    pdf.cell(200, 10, txt="This is an automated report generated by the Gemini AI & YOLOv8 Surveillance System.", ln=True, align='C')
    
    # 4. Save the PDF
    filename = f"Safety_Report_{datetime.now().strftime('%H%M%S')}.pdf"
    pdf.output(filename)
    
    return filename

# Note: This block is just for your friend to test if the file works locally.
if __name__ == "__main__":
    test_file = create_safety_report(max_crowd=45, alerts_triggered=3)
    print(f"Success! Report saved as: {test_file}")