from fpdf import FPDF
from datetime import datetime

def create_safety_report(peak_count, alert_count):
    pdf = FPDF()
    pdf.add_page()
    
    # 🛡️ Header
    pdf.set_font("Arial", 'B', 18)
    pdf.set_text_color(220, 53, 69) # Red color
    pdf.cell(200, 10, txt="SMART CROWD INTELLIGENCE", ln=True, align='C')
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(200, 10, txt="INCIDENT & SAFETY AUDIT REPORT", ln=True, align='C')
    pdf.line(10, 30, 200, 30)
    
    # 📅 Event Details
    pdf.ln(10)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 8, txt=f"Date & Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(200, 8, txt="Location: Pandharpur Wari / SVERI Main Campus", ln=True)
    pdf.cell(200, 8, txt="System Status: AUTOMATED AI GENERATED", ln=True)
    
    # 📊 Metrics
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Key Metrics:", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 8, txt=f"- Peak Crowd Count Detected: {peak_count} People", ln=True)
    pdf.cell(200, 8, txt=f"- Total Security Alerts Triggered: {alert_count} Alerts", ln=True)
    
    # 🧠 AI Post-Event Analysis & Advice
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="AI Post-Event Analysis & Tactical Advice:", ln=True)
    pdf.set_font("Arial", size=12)
    
    if peak_count > 30 or alert_count > 2:
         advice = "CRITICAL SITUATION DETECTED: The venue exceeded safe capacity limits. Immediate deployment of additional barricades and redirection of the queue at the Entry Gate is highly recommended to prevent stampede risks."
    else:
         advice = "SAFE OPERATIONS: The crowd flow was managed efficiently within normal limits. Spatial distribution remained optimal across all three zones. No severe anomalies were detected."
         
    pdf.multi_cell(0, 8, txt=advice)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(200, 10, txt="Generated by SVERI Predictive Public Safety Engine.", ln=True, align='C')
    
    # Save PDF
    file_name = "SVERI_Incident_Report.pdf"
    pdf.output(file_name)
    return file_name