from fpdf import FPDF
from datetime import datetime
import os

def create_safety_report(peak_count, alert_count):
    """
    Generates a professional PDF Safety Audit Report.
    Returns the filepath of the generated PDF.
    """
    # 'reports' नावाचे फोल्डर नसल्यास नवीन तयार करा
    if not os.path.exists("reports"):
        os.makedirs("reports")
        
    # फाईलचे नाव आणि वेळ
    current_time = datetime.now()
    timestamp = current_time.strftime("%Y%m%d_%H%M%S")
    date_str = current_time.strftime("%d %B %Y, %I:%M %p")
    filepath = f"reports/Security_Audit_{timestamp}.pdf"
    
    # PDF डिझाईन सुरू (FPDF)
    pdf = FPDF()
    pdf.add_page()
    
    # 1. 🏢 Header Section
    pdf.set_font("Arial", 'B', 18)
    pdf.set_text_color(0, 51, 102) # गडद निळा रंग (Professional)
    pdf.cell(200, 10, txt="SVERI SMART CROWD INTELLIGENCE", ln=True, align='C')
    
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(255, 68, 68) # लाल रंग
    pdf.cell(200, 10, txt="Post-Event Safety Audit Report", ln=True, align='C')
    
    pdf.ln(10) # रिकामी जागा
    
    # 2. 📅 Event Details
    pdf.set_font("Arial", '', 12)
    pdf.set_text_color(0, 0, 0) # काळा रंग
    pdf.cell(200, 10, txt=f"Report Generated On: {date_str}", ln=True, align='L')
    pdf.cell(200, 10, txt="Location: SVERI Main Campus / Event Venue", ln=True, align='L')
    pdf.line(10, 55, 200, 55) # एक रेष मारा
    pdf.ln(10)
    
    # 3. 📊 Executive Summary (Data)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="1. Executive Summary", ln=True, align='L')
    
    pdf.set_font("Arial", '', 12)
    pdf.cell(200, 10, txt=f"-> Peak Crowd Detected: {peak_count} individuals", ln=True, align='L')
    pdf.cell(200, 10, txt=f"-> Total Security Alerts Triggered: {alert_count}", ln=True, align='L')
    
    # Status Logic
    status = "SAFE" if alert_count < 5 else "HIGH RISK"
    pdf.cell(200, 10, txt=f"-> Overall Event Security Status: {status}", ln=True, align='L')
    pdf.ln(5)
    
    # 4. 🧠 AI Recommendations
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="2. AI System Recommendations", ln=True, align='L')
    
    pdf.set_font("Arial", '', 12)
    if alert_count > 5:
        pdf.multi_cell(0, 10, txt="Warning: The event experienced multiple overcrowding and proximity violations. It is highly recommended to increase security personnel and expand the venue capacity for future events.")
    else:
        pdf.multi_cell(0, 10, txt="Success: The event was managed effectively. Crowd density remained within safe limits and social distancing was properly maintained by the attendees.")
        
    pdf.ln(20)
    
    # 5. ✒️ Footer/Signature
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(200, 10, txt="Report auto-generated by SVERI AI Crowd Engine (YOLOv8 + Gemini)", ln=True, align='C')
    
    # PDF सेव्ह करा
    pdf.output(filepath)
    return filepath

# Local Testing
if __name__ == "__main__":
    print("Generating Test Report...")
    test_file = create_safety_report(peak_count=150, alert_count=8)
    print(f"✅ Report successfully generated at: {test_file}")